# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x63tion_log.proto\x12\x10ident.action_log\"\x9c\x01\n\tActionLog\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x32\n\x07sign_in\x18\xe8\x07 \x01(\x0b\x32\x1e.ident.action_log.ActionSignInH\x00\x12\x34\n\x08sign_out\x18\xe9\x07 \x01(\x0b\x32\x1f.ident.action_log.ActionSignOutH\x00\x42\x08\n\x06\x61\x63tion\"!\n\x0c\x41\x63tionSignIn\x12\x11\n\tsource_ip\x18\x01 \x01(\t\"\x0f\n\rActionSignOutb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONLOG._serialized_start=39
  _ACTIONLOG._serialized_end=195
  _ACTIONSIGNIN._serialized_start=197
  _ACTIONSIGNIN._serialized_end=230
  _ACTIONSIGNOUT._serialized_start=232
  _ACTIONSIGNOUT._serialized_end=247
# @@protoc_insertion_point(module_scope)
