# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pplication.proto\x12\x11ident.application\"t\n\x04Rule\x12\n\n\x02id\x18\x01 \x01(\x04\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.ident.application.AccessRuleType\x12\x11\n\x07user_id\x18\x03 \x01(\x04H\x00\x12\x12\n\x08group_id\x18\x04 \x01(\x04H\x00\x42\x08\n\x06target\"O\n\x0b\x41pplication\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12&\n\x05rules\x18\x03 \x03(\x0b\x32\x17.ident.application.Rule*+\n\x0e\x41\x63\x63\x65ssRuleType\x12\x0c\n\x08\x41RTAllow\x10\x00\x12\x0b\n\x07\x41RTDeny\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'application_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCESSRULETYPE._serialized_start=239
  _ACCESSRULETYPE._serialized_end=282
  _RULE._serialized_start=40
  _RULE._serialized_end=156
  _APPLICATION._serialized_start=158
  _APPLICATION._serialized_end=237
# @@protoc_insertion_point(module_scope)
