# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network_policy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14network_policy.proto\x12\x14ident.network_policy\"d\n\rNetworkPolicy\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x35\n\x04type\x18\x02 \x01(\x0e\x32\'.ident.network_policy.NetworkPolicyType\x12\x10\n\x08selector\x18\x03 \x01(\t*0\n\x11NetworkPolicyType\x12\r\n\tNPRTAllow\x10\x00\x12\x0c\n\x08NPRTDeny\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_policy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NETWORKPOLICYTYPE._serialized_start=148
  _NETWORKPOLICYTYPE._serialized_end=196
  _NETWORKPOLICY._serialized_start=46
  _NETWORKPOLICY._serialized_end=146
# @@protoc_insertion_point(module_scope)
