# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\nident.user\"\xe6\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.ident.user.UserType\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x12\n\navatar_url\x18\x05 \x01(\t\x12\x34\n\nattributes\x18\x06 \x03(\x0b\x32 .ident.user.User.AttributesEntry\x12\x10\n\x08password\x18\x07 \x01(\x0c\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*#\n\x08UserType\x12\n\n\x06UTUser\x10\x00\x12\x0b\n\x07UTAdmin\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER_ATTRIBUTESENTRY._options = None
  _USER_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _USERTYPE._serialized_start=259
  _USERTYPE._serialized_end=294
  _USER._serialized_start=27
  _USER._serialized_end=257
  _USER_ATTRIBUTESENTRY._serialized_start=208
  _USER_ATTRIBUTESENTRY._serialized_end=257
# @@protoc_insertion_point(module_scope)
