# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webhook.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwebhook.proto\x12\rident.webhook\"\x0f\n\rWebhookFilter\"Q\n\x07Webhook\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03url\x18\x02 \x01(\t\x12-\n\x07\x66ilters\x18\x03 \x03(\x0b\x32\x1c.ident.webhook.WebhookFilterb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webhook_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBHOOKFILTER._serialized_start=32
  _WEBHOOKFILTER._serialized_end=47
  _WEBHOOK._serialized_start=49
  _WEBHOOK._serialized_end=130
# @@protoc_insertion_point(module_scope)
